export const ARTICLES = [
  {
    id: 1,
    title: "Welcome to scribble",
    category: "Front End Articles",
    author: "Oliver smith",
    lastPublished: "Jul 13, 2022, 11:13 AM",
    status: "Draft",
  },
  {
    id: 2,
    title: "Welcome to scribble",
    category: "Front End Articles",
    author: "Oliver smith",
    lastPublished: "Jul 13, 2022, 11:13 AM",
    status: "Draft",
  },
  {
    id: 3,
    title: "Welcome to scribble",
    category: "Front End Articles",
    author: "Oliver smith",
    lastPublished: "Jul 13, 2022, 11:13 AM",
    status: "Draft",
  },
  {
    id: 4,
    title: "Welcome to scribble",
    category: "Front End Articles",
    author: "Oliver smith",
    lastPublished: "Jul 13, 2022, 11:13 AM",
    status: "Draft",
  },
  {
    id: 5,
    title: "Welcome to scribble",
    category: "Front End Articles",
    author: "Oliver smith",
    lastPublished: "Jul 13, 2022, 11:13 AM",
    status: "Draft",
  },
  {
    id: 6,
    title: "Welcome to scribble",
    category: "Front End Articles",
    author: "Oliver smith",
    lastPublished: "Jul 13, 2022, 11:13 AM",
    status: "Draft",
  },
  {
    id: 7,
    title: "Welcome to scribble",
    category: "Front End Articles",
    author: "Oliver smith",
    lastPublished: "Jul 13, 2022, 11:13 AM",
    status: "Draft",
  },
  {
    id: 8,
    title: "Welcome to scribble",
    category: "Front End Articles",
    author: "Oliver smith",
    lastPublished: "Jul 13, 2022, 11:13 AM",
    status: "Draft",
  },
  {
    id: 9,
    title: "Welcome to scribble",
    category: "Front End Articles",
    author: "Oliver smith",
    lastPublished: "Jul 13, 2022, 11:13 AM",
    status: "Draft",
  },
  {
    id: 10,
    title: "Welcome to scribble",
    category: "Front End Articles",
    author: "Oliver smith",
    lastPublished: "Jul 13, 2022, 11:13 AM",
    status: "Draft",
  },
  {
    id: 11,
    title: "Welcome to scribble",
    category: "Front End Articles",
    author: "Oliver smith",
    lastPublished: "Jul 13, 2022, 11:13 AM",
    status: "Draft",
  },
  {
    id: 12,
    title: "Welcome to scribble",
    category: "Front End Articles",
    author: "Oliver smith",
    lastPublished: "Jul 13, 2022, 11:13 AM",
    status: "Draft",
  },
  {
    id: 13,
    title: "Welcome to scribble",
    category: "Front End Articles",
    author: "Oliver smith",
    lastPublished: "Jul 13, 2022, 11:13 AM",
    status: "Draft",
  },
  {
    id: 14,
    title: "Welcome to scribble",
    category: "Front End Articles",
    author: "Oliver smith",
    lastPublished: "Jul 13, 2022, 11:13 AM",
    status: "Draft",
  },
];
